on: push
name: CICD Pipeline
jobs:
  build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
  web-deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 54.153.205.124
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /uat/admin/
